const NEW_PASSWORD_INITIAL = 'NEW_PASSWORD_INITIAL';

const NEW_UPDATE_PASSWORD = 'NEW_UPDATE_PASSWORD';
const NEW_SHOW_PASSWORD   = 'NEW_SHOW_PASSWORD';
const NEW_NO_PASSWORD = 'NEW_NO_PASSWORD';

const NEW_PASSWORD_ZERO_LENGTH = 'NEW_PASSWORD_ZERO_LENGTH';
const NEW_PASSWORD_LESS_LENGTH = 'NEW_PASSWORD_LESS_LENGTH';
const NEW_PASSWORD_WEAK   = 'NEW_PASSWORD_WEAK';
const NEW_PASSWORD_MEDIUM = 'NEW_PASSWORD_MEDIUM';
const NEW_PASSWORD_STRONG = 'NEW_PASSWORD_STRONG';

export {
    NEW_PASSWORD_INITIAL,
    NEW_UPDATE_PASSWORD,
    NEW_SHOW_PASSWORD,
    NEW_NO_PASSWORD,
    NEW_PASSWORD_ZERO_LENGTH,
    NEW_PASSWORD_LESS_LENGTH,
    NEW_PASSWORD_WEAK,
    NEW_PASSWORD_MEDIUM,
    NEW_PASSWORD_STRONG
};