const LOGIN_RAISE_CURTAIN   = 'LOGIN_RAISE_CURTAIN';
const LOGIN_UPDATE_EMAIL    = 'LOGIN_UPDATE_EMAIL';
const LOGIN_UPDATE_PASSWORD = 'LOGIN_UPDATE_PASSWORD';
const LOGIN_EMAIL_SHOW_WARNING   = 'LOGIN_EMAIL_SHOW_WARNING';
const LOGIN_EMAIL_NO_WARNING   = 'LOGIN_EMAIL_NO_WARNING';

const LOGIN_SHOW_PASSWORD   = 'LOGIN_SHOW_PASSWORD';
const LOGIN_NO_PASSWORD = 'LOGIN_NO_PASSWORD';

const LOGIN_PASSWORD_ZERO_LENGTH = 'LOGIN_PASSWORD_ZERO_LENGTH';
const LOGIN_PASSWORD_LESS_LENGTH = 'LOGIN_PASSWORD_LESS_LENGTH';
const LOGIN_PASSWORD_WEAK   = 'LOGIN_PASSWORD_WEAK';
const LOGIN_PASSWORD_MEDIUM = 'LOGIN_PASSWORD_MEDIUM';
const LOGIN_PASSWORD_STRONG = 'LOGIN_PASSWORD_STRONG';

export {
    LOGIN_RAISE_CURTAIN,
    LOGIN_UPDATE_EMAIL,
    LOGIN_UPDATE_PASSWORD,
    LOGIN_EMAIL_SHOW_WARNING,
    LOGIN_EMAIL_NO_WARNING,
    LOGIN_SHOW_PASSWORD,
    LOGIN_NO_PASSWORD,
    LOGIN_PASSWORD_ZERO_LENGTH,
    LOGIN_PASSWORD_LESS_LENGTH,
    LOGIN_PASSWORD_WEAK,
    LOGIN_PASSWORD_MEDIUM,
    LOGIN_PASSWORD_STRONG,
};