const TRANSACTION_MAP_CHAT_DETAILS       = 'TRANSACTION_MAP_CHAT_DETAILS';
const TRANSACTION_MAP_CHAT_FROM_FOUNDED  = 'TRANSACTION_MAP_CHAT_FROM_FOUNDED';
const TRANSACTION_MAP_CHAT_TO_FOUNDED    = 'TRANSACTION_MAP_CHAT_TO_FOUNDED';
const TRANSACTION_MAP_CHAT_FROM_LOCATION = 'TRANSACTION_MAP_CHAT_FROM_LOCATION';
const TRANSACTION_MAP_CHAT_TO_LOCATION   = 'TRANSACTION_MAP_CHAT_TO_LOCATION';
const TRANSACTION_CHAT   = 'TRANSACTION_CHAT';

const TRANSACTION_LIVE_MODE = 'TRANSACTION_LIVE_MODE';
const TRANSACTION_SUCCESS_MODE = 'TRANSACTION_SUCCESS_MODE';
const TRANSACTION_CANCEL_MODE = 'TRANSACTION_CANCAL_MODE';
const TRANSACTION_TIME_EXPIRED_MODE = 'TRANSACTION_TIME_EXPIRED_MODE';

export {
    TRANSACTION_MAP_CHAT_DETAILS,
    TRANSACTION_MAP_CHAT_FROM_FOUNDED,
    TRANSACTION_MAP_CHAT_TO_FOUNDED,
    TRANSACTION_MAP_CHAT_FROM_LOCATION,
    TRANSACTION_MAP_CHAT_TO_LOCATION,
    TRANSACTION_CHAT,

    TRANSACTION_LIVE_MODE,
    TRANSACTION_SUCCESS_MODE,
    TRANSACTION_CANCEL_MODE,
    TRANSACTION_TIME_EXPIRED_MODE

}

