const TRANSACTION_MAP_CHAT_DETAILS       = 'TRANSACTION_MAP_CHAT_DETAILS';
const TRANSACTION_MAP_CHAT_FROM_FOUNDED  = 'TRANSACTION_MAP_CHAT_FROM_FOUNDED';
const TRANSACTION_MAP_CHAT_TO_FOUNDED    = 'TRANSACTION_MAP_CHAT_TO_FOUNDED';
const TRANSACTION_MAP_CHAT_FROM_LOCATION = 'TRANSACTION_MAP_CHAT_FROM_LOCATION';
const TRANSACTION_MAP_CHAT_TO_LOCATION   = 'TRANSACTION_MAP_CHAT_TO_LOCATION';

export {
    TRANSACTION_MAP_CHAT_DETAILS,
    TRANSACTION_MAP_CHAT_FROM_FOUNDED,
    TRANSACTION_MAP_CHAT_TO_FOUNDED,
    TRANSACTION_MAP_CHAT_FROM_LOCATION,
    TRANSACTION_MAP_CHAT_TO_LOCATION
}