const REDIRECT_TO_TRANSACTION_USER_PROFILE  = 'REDIRECT_TO_TRANSACTION_USER_PROFILE';

const USER_PROFILE_REQUEST_SEND = 'USER_PROFILE_REQUEST_SEND';
const USER_PROFILE_REQUEST_CANCEL = 'USER_PROFILE_REQUEST_CANCEL';
const USER_PROFILE_REQUEST_TIMER_EXPIRED = 'USER_PROFILE_REQUEST_TIMER_EXPIRED';
const USER_PROFILE_REQUEST_ACCEPTED = 'USER_PROFILE_REQUEST_ACCEPTED';
const USER_PROFILE_REQUEST_REJECTED = 'USER_PROFILE_REQUEST_REJECTED';

export {
    REDIRECT_TO_TRANSACTION_USER_PROFILE,
    
    // USER_PROFILE_REQUEST_NOT,
    USER_PROFILE_REQUEST_SEND,
    USER_PROFILE_REQUEST_CANCEL,
    USER_PROFILE_REQUEST_TIMER_EXPIRED,
    USER_PROFILE_REQUEST_ACCEPTED,
    USER_PROFILE_REQUEST_REJECTED
}