const LOGIN_FORGOT_PASSWORD_INITIAL = 'LOGIN_FORGOT_PASSWORD_INITIAL';

const LOGIN_FORGOT_PASSWORD_UPDATE_EMAIL = 'LOGIN_FORGOT_PASSWORD_UPDATE_EMAIL';
const LOGIN_FORGOT_PASSWORD_SHOW_WARNING = 'LOGIN_FORGOT_PASSWORD_SHOW_WARNING';
const LOGIN_FORGOT_PASSWORD_NO_WARNING = 'LOGIN_FORGOT_PASSWORD_NO_WARNING';

export {
    LOGIN_FORGOT_PASSWORD_INITIAL,
    LOGIN_FORGOT_PASSWORD_UPDATE_EMAIL,
    LOGIN_FORGOT_PASSWORD_SHOW_WARNING,
    LOGIN_FORGOT_PASSWORD_NO_WARNING
}