const PROFILE_LOG_IN = 'PROFILE_LOG_IN';
const PROFILE_LOG_OUT = 'PROFILE_LOG_OUT';
const PROFILE_SIGN_UP = 'PROFILE_SIGN_UP';
const PROFILE_SIGN_UP_VERIFIED = 'PROFILE_SIGN_UP_VERIFIED';
 
export {
    PROFILE_LOG_IN,
    PROFILE_LOG_OUT, 
    PROFILE_SIGN_UP, 
    PROFILE_SIGN_UP_VERIFIED 
};