const REDIRECT_TO_LOADING  = 'REDIRECT_TO_LOADING';
const REDIRECT_TO_MAINPAGE = 'REDIRECT_TO_MAINPAGE';
const REDIRECT_TO_LOGIN = 'REDIRECT_TO_LOGIN';
const REDIRECT_TO_FORGET_USERNAME = 'REDIRECT_TO_FORGET_USERNAME';
const REDIRECT_TO_FORGET_PASSWORD = 'REDIRECT_TO_FORGET_PASSWORD';
const REDIRECT_TO_FORGET_PASSWORD_OTP = 'REDIRECT_TO_FORGET_PASSWORD_OTP';
const REDIRECT_TO_NEW_PASSWORD = 'REDIRECT_TO_NEW_PASSWORD';

const REDIRECT_TO_SIGNUP = 'REDIRECT_TO_SIGNUP';
const REDIRECT_TO_SIGNUP_OTP = 'REDIRECT_TO_SIGNUP_OTP';
const REDIRECT_TO_PERSONAL_DETAILS = 'REDIRECT_TO_SIGNUP_PERSONAL_DETAILS';


export {
    REDIRECT_TO_LOADING,
    REDIRECT_TO_MAINPAGE,
    REDIRECT_TO_FORGET_USERNAME,
    REDIRECT_TO_LOGIN, 
    REDIRECT_TO_FORGET_PASSWORD, 
    REDIRECT_TO_FORGET_PASSWORD_OTP, 
    REDIRECT_TO_NEW_PASSWORD, 
    REDIRECT_TO_SIGNUP, 
    REDIRECT_TO_SIGNUP_OTP, 
    REDIRECT_TO_PERSONAL_DETAILS, 
};