const LOGIN_FORGOT_PASSWORD_OTP_INITIAL = 'LOGIN_FORGOT_PASSWORD_OTP_INITIAL';

const LOGIN_FORGOT_PASSWORD_OTP_UPDATE_OTP = 'LOGIN_FORGOT_PASSWORD_OTP_UPDATE_OTP';
const LOGIN_FORGOT_PASSWORD_OTP_SHOW_WARNING = 'LOGIN_FORGOT_PASSWORD_OTP_SHOW_WARNING';
const LOGIN_FORGOT_PASSWORD_OTP_NO_WARNING   = 'LOGIN_FORGOT_PASSWORD_OTP_NO_WARNING';

export {
    LOGIN_FORGOT_PASSWORD_OTP_INITIAL,
    LOGIN_FORGOT_PASSWORD_OTP_UPDATE_OTP,
    LOGIN_FORGOT_PASSWORD_OTP_SHOW_WARNING,
    LOGIN_FORGOT_PASSWORD_OTP_NO_WARNING
}