// const NOT_SEARCHED = 'NOT_SEARCHED';
const SEARCHED = 'SEARCHED';
const REQUEST_GONE = 'REQUEST_GONE';
const REQUEST_ACCEPTED = 'REQUEST_ACCEPTED';
// const REQUEST_REJECTED = 'REQUEST_REJECTED';
const SAVED = 'SAVED';
const REQUEST_CAME = 'REQUEST_CAME';
const FOUND_USER = 'FOUND_USER';
// const CANT_FOUND = 'CANT_FOUND';
// const NOT_SCANNED = 'NOT_SCANNED';
// const SCANNED = 'SCANNED';
const FEEDBACK_STATE = 'FEEDBACK_STATE';

export {
    SEARCHED,
    REQUEST_GONE,
    REQUEST_ACCEPTED,
    SAVED,
    REQUEST_CAME,
    FOUND_USER,
    FEEDBACK_STATE
};