const ABOUT = 'ABOUT';
const LOGIN = 'LOGIN';
const FORGET_PASSWORD = 'FORGET_PASSWORD';
const FORGET_PASSWORD_OTP = 'FORGET_PASSWORD_OTP';
const NEW_PASSWORD = 'NEW_PASSWORD';

const SIGNUP = 'SIGNUP';
const SIGNUP_OTP = 'SIGNUP_OTP';
const SIGNUP_PERSONAL_DETAILS = 'SIGNUP_PERSONAL_DETAILS';

const MAINPAGE = 'MAINPAGE';

const PROFILE = 'PROFILE';
const EDIT_DETAILS = 'EDIT_DETAILS';
const EDIT_PASSWORD = 'EDIT_PASSWORD';
const ADD_NEW_PASSWORD = 'ADD_NEW_PASSWORD';
const USER_SETTINGS = 'USER_SETTINGS';
const APPLICATION_SUPPORT = 'SUPPORT';
const APPLICATION_FEEDBACK = 'FEEDBACK';

const HISTORY = 'HISTORY';
const HISTORY_TRANSACTION = 'HISTORY_TRANSACTION';
const HISTORY_TRANSACTION_CHAT = 'HISTORY_TRANSACTION_CHAT';

const NOTIFICATION = 'NOTIFICATION';

const SEARCH = 'SEARCH';
const USER_PROFILE = 'USER_PROFILE';
const MAP_CHAT = 'MAP_CHAT';
const SCAN_QR = 'SCAN_QR';
const FEEDBACK = 'FEEDBACK';

export {
    ABOUT, 
    LOGIN, 
    FORGET_PASSWORD, 
    FORGET_PASSWORD_OTP, 
    NEW_PASSWORD, 
    SIGNUP, 
    SIGNUP_OTP, 
    SIGNUP_PERSONAL_DETAILS, 
    MAINPAGE, 
    PROFILE, 
    EDIT_DETAILS, 
    EDIT_PASSWORD, 
    ADD_NEW_PASSWORD, 
    USER_SETTINGS, 
    APPLICATION_SUPPORT, 
    APPLICATION_FEEDBACK, 
    HISTORY, 
    HISTORY_TRANSACTION, 
    HISTORY_TRANSACTION_CHAT, 
    NOTIFICATION, 
    SEARCH, 
    USER_PROFILE, 
    MAP_CHAT, 
    SCAN_QR, 
    FEEDBACK
}