const REDIRECT_TO_PROFILE = 'REDIRECT_TO_PROFILE';
const REDIRECT_TO_HISTORY = 'REDIRECT_TO_HISTORY';
const REDIRECT_TO_NOTIFICATION = 'REDIRECT_TO_NOTIFICATION';
const REDIRECT_TO_TRANSACTION_SEARCH = 'REDIRECT_TO_TRANSACTION_SEARCH';

const REDIRECT_TO_TRANSACTION_MAP_CHAT      = 'REDIRECT_TO_TRANSACTION_MAP_CHAT';
const REDIRECT_TO_TRANSACTION_SCAN_QR       = 'REDIRECT_TO_TRANSACTION_SCAN_QR';
const REDIRECT_TO_TRANSACTION_FEEDBACK_PAGE = 'REDIRECT_TO_TRANSACTION_FEEDBACK_PAGE';

const MAINPAGE_UPDATE_DETAILS = 'MAINPAGE_UPDATE_DETAILS';

export {
    REDIRECT_TO_HISTORY,
    REDIRECT_TO_PROFILE,
    REDIRECT_TO_NOTIFICATION,
    REDIRECT_TO_TRANSACTION_SEARCH,
    
    REDIRECT_TO_TRANSACTION_MAP_CHAT,
    REDIRECT_TO_TRANSACTION_SCAN_QR,
    REDIRECT_TO_TRANSACTION_FEEDBACK_PAGE,

    MAINPAGE_UPDATE_DETAILS,
};