const REDIRECT_TO_PROFILE = 'REDIRECT_TO_PROFILE';
const REDIRECT_TO_HISTORY = 'REDIRECT_TO_HISTORY';
const REDIRECT_TO_NOTIFICATION = 'REDIRECT_TO_NOTIFICATION';
const REDIRECT_TO_TRANSACTION_SEARCH = 'REDIRECT_TO_TRANSACTION_SEARCH';

const REDIRECT_TO_TRANSACTION_MAP_CHAT      = 'REDIRECT_TO_TRANSACTION_MAP_CHAT';
const REDIRECT_TO_TRANSACTION_SCAN_QR       = 'REDIRECT_TO_TRANSACTION_SCAN_QR';
const REDIRECT_TO_TRANSACTION_FEEDBACK_PAGE = 'REDIRECT_TO_TRANSACTION_FEEDBACK_PAGE';

const MAINPAGE_SEARCH_MODE = 'MAINPAGE_SEARCH_MODE';
const MAINPAGE_SAVED_MODE  = 'MAINPAGE_SAVED_MODE';
const MAINPAGE_TRANSACTION_MODE = 'MAINPAGE_TRANSACTION_MODE';
const MAINPAGE_SHARE_MODE  = 'MAINPAGE_SHARE_MODE';
const MAINPAGE_FEEDBACK_MODE = 'MAINPAGE_FEEDBACK_MODE';

const MAINPAGE_LAST_SEARCH            = 'MAINPAGE_LAST_SEARCH';
const MAINPAGE_LAST_SEARCH_RESULTS    = 'MAINPAGE_LAST_SEARCH_RESULTS';
const MAINPAGE_LAST_SEARCH_SAVED_UPTO = 'MAINPAGE_LAST_SEARCH_SAVED_UPTO';

const MAINPAGE_CURRENT_TRANSACTION = 'MAINPAGE_CURRENT_TRANSACTION';

const MAINPAGE_REQUEST_RECEIVED = 'MAINPAGE_REQUEST_RECEIVED';  

const MAINPAGE_UPDATE_CONSTANTS = 'MAINPAGE_UPDATE_CONSTANTS';

const MAINPAGE_TRANSACTION_END_TIME = 'MAINPAGE_TRANSACTION_END_TIME';

export {
    REDIRECT_TO_HISTORY,
    REDIRECT_TO_PROFILE,
    REDIRECT_TO_NOTIFICATION,
    REDIRECT_TO_TRANSACTION_SEARCH,
    
    REDIRECT_TO_TRANSACTION_MAP_CHAT,
    REDIRECT_TO_TRANSACTION_SCAN_QR,
    REDIRECT_TO_TRANSACTION_FEEDBACK_PAGE,

    MAINPAGE_SEARCH_MODE,
    MAINPAGE_SAVED_MODE,
    MAINPAGE_TRANSACTION_MODE,
    MAINPAGE_SHARE_MODE,
    MAINPAGE_FEEDBACK_MODE,

    MAINPAGE_LAST_SEARCH,
    MAINPAGE_LAST_SEARCH_RESULTS,
    MAINPAGE_LAST_SEARCH_SAVED_UPTO,

    MAINPAGE_CURRENT_TRANSACTION,
    MAINPAGE_REQUEST_RECEIVED,

    MAINPAGE_UPDATE_CONSTANTS,
    MAINPAGE_TRANSACTION_END_TIME
};