const REDIRECT_TO_PROFILE = 'REDIRECT_TO_PROFILE';
const REDIRECT_TO_HISTORY = 'REDIRECT_TO_HISTORY';
const REDIRECT_TO_NOTIFICATION = 'REDIRECT_TO_NOTIFICATION';
const REDIRECT_TO_TRANSACTION_SEARCH = 'REDIRECT_TO_TRANSACTION_SEARCH';

const REDIRECT_TO_TRANSACTION_MAP_CHAT      = 'REDIRECT_TO_TRANSACTION_MAP_CHAT';
const REDIRECT_TO_TRANSACTION_SCAN_QR       = 'REDIRECT_TO_TRANSACTION_SCAN_QR';
const REDIRECT_TO_TRANSACTION_FEEDBACK_PAGE = 'REDIRECT_TO_TRANSACTION_FEEDBACK_PAGE';

const MAINPAGE_SEARCH_MODE = 'MAINPAGE_SEARCH_MODE';
const MAINPAGE_SAVED_MODE  = 'MAINPAGE_SAVED_MODE';
const MAINPAGE_TRANSACTION_MODE = 'MAINPAGE_TRANSACTION_MODE';
const MAINPAGE_SHARE_MODE  = 'MAINPAGE_SHARE_MODE';
const MAINPAGE_FEEDBACK_MODE = 'MAINPAGE_FEEDBACK_MODE';

const MAINPAGE_UPDATE_SEARCH_DETAILS = 'MAINPAGE_UPDATE_SEARCH_DETAILS';
const MAINPAGE_UPDATE_SEARCH_RESULTS = 'MAINPAGE_UPDATE_SEARCH_RESULTS';
const UPDATE_SOCKET = 'UPDATE_SOCKET';

export {
    REDIRECT_TO_HISTORY,
    REDIRECT_TO_PROFILE,
    REDIRECT_TO_NOTIFICATION,
    REDIRECT_TO_TRANSACTION_SEARCH,
    
    REDIRECT_TO_TRANSACTION_MAP_CHAT,
    REDIRECT_TO_TRANSACTION_SCAN_QR,
    REDIRECT_TO_TRANSACTION_FEEDBACK_PAGE,

    MAINPAGE_SEARCH_MODE,
    MAINPAGE_SAVED_MODE,
    MAINPAGE_TRANSACTION_MODE,
    MAINPAGE_SHARE_MODE,
    MAINPAGE_FEEDBACK_MODE,

    MAINPAGE_UPDATE_SEARCH_DETAILS,
    MAINPAGE_UPDATE_SEARCH_RESULTS,
    UPDATE_SOCKET
};